# Generated by Django 5.0.1 on 2024-01-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='targetpage',
            field=models.CharField(default=0, max_length=50, verbose_name='Trg'),
            preserve_default=False,
        ),
    ]
